#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Weather_Assignment.Resource", IsApplication=true)]

namespace Android_Weather_Assignment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chanceflurries = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chancerain = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chancesleet = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chancesnow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int chancetstorms = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int clear = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cloudy = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flurries = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fog = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hazy = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mostlycloudy = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mostlysunny = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int nt_chanceflurries = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int nt_chancerain = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int nt_chancesleet = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int nt_chancesnow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int nt_chancetstorms = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int nt_clear = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int nt_cloudy = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int nt_flurries = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int nt_fog = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int nt_hazy = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int nt_mostlycloudy = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int nt_mostlysunny = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int nt_partlycloudy = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int nt_partlysunny = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int nt_rain = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int nt_sleet = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int nt_snow = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int nt_sunny = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int nt_tstorms = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int partlycloudy = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int partlysunny = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int rain = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sleet = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int snow = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int sunny = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tstorms = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int analogClock1 = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int iv_Image = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int lv_CityWeather = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int lv_Forecast = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int tv_CityName = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int tv_CurrentStation = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int tv_CurrentTemp = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int tv_Date = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int tv_Day = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tv_HighTemp = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int tv_HumidityData = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int tv_HumidityTitle = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int tv_LowTemp = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int tv_Temp = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int tv_TempTitle = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CityItemLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CurrentLocation = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Forecast = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ForecastItemLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
